### PR TITLE
Integrate mailchimp

### LINKED ISSUE #2: Finish implementing mailchimp form
api endpoint is setup - just needs to be implemented client side with appropriate rendering of the returned list

### PR DESCRIPTION
**Pull request by jeremiak**
Hey @rossPatton, this isn't done yet, but should close #2.

Uses the mailchimp proxy to pull the names and render them in a new component. I also started to hook up the form but didn't finish. The site sends the data from the form to the mailchimp proxy, but it still needs to be formatted properly for the mailchimp API.

### CODE REVIEW

**Comment by rossPatton** [comment]
hah, so, i was just about to push this up. you beat me by about 20 minutes

**Comment by jeremiak** [comment]
Ah shoot, sorry about that! Let's go with yours if its further along

**Comment by rossPatton** [comment]
nah, i hadn't implemented the submit yet. i'll take what you've done and just build on that

**Comment by jeremiak** [comment]
👍🏼

**Pull request merged**
